[project]
name = "fastroutes"
version = "0.1.0"
description = "Generate HTTP clients from FastAPI apps"
authors = [{ name = "draew6" }]
dependencies = [
    "fastapi",
    "httpx",
    "typer[all]",
    "pydantic>=2.0"
]
readme = "README.md"
requires-python = ">=3.9"

[project.scripts]
fastroutes = "fastroutes.cli:generate"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
